In [1]:
import numpy as np


# creating numpy ndarray

In [2]:
import numpy as np

In [9]:
#one dimensional array
arr1=np.array([2,3,4])

In [4]:
arr1

array([2, 3, 4])

In [10]:
#array type checking
type(arr1)

numpy.ndarray

In [11]:
#2dimensional array
arr2=np.array([[1,2,3,4],[1,2,4,5]])

In [12]:
arr2

array([[1, 2, 3, 4],
       [1, 2, 4, 5]])

In [14]:
#checking the shape of an array
arr2.shape

(2, 4)

In [17]:
# Create an array of all zeros
arr3=np.zeros((3,3))

In [18]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# Create an array of all ones
arr4=np.ones((3,3))

In [20]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# Create a constant array
arr5=np.full((2,2), 7)

In [22]:
arr5


array([[7, 7],
       [7, 7]])

In [23]:
# Create a 2x2 identity matrix
arr6=np.identity((2))

In [24]:
arr6

array([[1., 0.],
       [0., 1.]])

In [25]:
arr6=np.eye((2))

In [26]:
arr6

array([[1., 0.],
       [0., 1.]])

In [32]:
# Create an array filled with random values
arr7=np.random.random((2,2))

In [33]:
arr7

array([[0.9589578 , 0.79650681],
       [0.94491211, 0.18474101]])

In [36]:
# range in numpy
arr8=np.arange(2,10)

In [37]:
arr8

array([2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr8=np.arange(2,10,3)

In [43]:
arr8

array([2, 5, 8])

In [48]:
#Returns num evenly spaced samples, calculated over the interval [start, stop].
arr9=np.linspace(2,10,3)

In [49]:
arr9

array([ 2.,  6., 10.])

In [50]:
#copying array 
arr10=np.copy(arr1)

In [51]:
arr10

array([2, 3, 4])

#numpy properties and attributes

In [55]:
array_A = np.array([ [3,4,6], [0,8,1] ])
array_A

array([[3, 4, 6],
       [0, 8, 1]])

In [53]:
#ndarray.ndim =ndim represents the number of dimensions (axes) of the ndarray.
array_A.ndim

2

In [54]:
#ndarray.shape=shape is a tuple of integers representing the size of the ndarray in each dimension
array_A.shape

(2, 3)

In [56]:
#ndarray.size=size is the total number of elements in the ndarray. It is equal to the product of elements of the shape.
array_A.size

6

In [57]:
# ndarray.dtype=dtype tells the data type of the elements of a NumPy array. In NumPy array, all the elements have the same data type.
array_A.dtype

dtype('int64')

In [58]:
#ndarray.itemsize=itemsize returns the size (in bytes) of each element of a NumPy array.
array_A.itemsize

8

In [59]:
#NumPy also provides a reshape function to resize an array
array_A.reshape(3,2)

array([[3, 4],
       [6, 0],
       [8, 1]])

In [60]:
#converting the datatype
array_A.astype('float')

array([[3., 4., 6.],
       [0., 8., 1.]])

#Indexing, Slicing and Iteration

In [62]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
arr1=np.array([lst1,lst2,lst3])

In [63]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [65]:
#indexing
arr1[2]

array([3, 4, 5, 6, 7])

In [68]:
arr1[2]=[7,6,5,4,3]
arr1


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [7, 6, 5, 4, 3]])

In [73]:
arr1[0:2]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [97]:
n_array=[7,6,5,4,3]

In [78]:
# print all value
n_array[:]

[7, 6, 5, 4, 3]

In [83]:
#print only one value
n_array[-3]

5

In [87]:
#if we want to print all value without 5
n_array[2:3]

[5, 4, 3]

In [92]:
arr1[1:2,1:3]

array([[3, 4]])

In [111]:
#if we want to print all value without 5
array=np.array([7,6,5,4,3])
array

array([7, 6, 5, 4, 3])

In [112]:
index=-3

In [113]:
n_array=np.delete(array,index)

In [110]:
n_array

array([7, 6, 4, 3])

In [115]:
# if we want to print reverse of the array
n_array[::-1]

array([3, 4, 6, 7])

In [116]:
n_array[::-2]

array([3, 6])

In [124]:
index=arr1[:,1:4]

array([[2, 3, 4],
       [3, 4, 5],
       [6, 5, 4]])

In [131]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [132]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [134]:
arr1[:,::4]

array([[1, 5],
       [2, 6],
       [3, 7]])